version: '3.3'

services:
  bot:
    build: .
    volumes:
      - ./:/app
    environment:
      NODE_ENV: dev
    depends_on:
      - redis
    command: ["run", "start-dev"]
  redis:
    image: redis:latest
